# Generated by Django 3.2.12 on 2024-03-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilestat',
            name='No_of_game_draw',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profilestat',
            name='No_of_game_won',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profilestat',
            name='No_of_games_played',
            field=models.BigIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Game_history',
        ),
    ]
